### PR TITLE
Enable start-end-input-mode when adding time entries

### PR DESCRIPTION
**Pull request by te-online**
*This is based on work by @devattendant*

---

These are the areas I'd like to investigate and/or improve before merging 🤓 

- [x] In `helpers.js`: Remove all JS warnings, use date-fns where possible to improve compatibility and DX
- [x] Improve UX of QuickAdd by allowing to switch between different modes instead of offering both at the same time (the label is simply too long and we have too many inputs in the current design) -> first approach for review
- [x] Investigate if we absolutely need to provide timezones for statistics
- [x] Investigate if we absolutely need a new user setting for the timezone
- [x] Remove dependency on jQuery for converting dates to user's timezone

### CODE REVIEW

**Comment by te-online** [comment]
@devattendant What do you think about this UI approach? It reduces the amount of space used, but shows all the fields during interaction. I feel like it's a good compromise, but would like to hear your opinion 😊 

Screenshot 2022-11-08 at 00 38 17
Screenshot 2022-11-08 at 00 45 28

**Comment by te-online** [comment]
Hey @devattendant – I've update the PR with a slightly simplified version 🙂 

I tested a bit by setting my computer's timezone to something else and I think it works as expected.

But I could really use your help to test if these changes still address the issues you had with timezones. Does it work on your end? 🙏

**Comment by devattendant** [comment]
Hi @te-online,

Sorry for not replying earlier. Right now I sadly do not have enough time to have a look at your changes and test them. This might change in February earliest but I cannot promise that unfortunately as well :/

**Comment by 31SFX4** [comment]
(Just a little encouragement, I hope this is not adding unnecessary noise to the thread..:) Thanks for your work on this improvement, I'm really looking forward to being able to record start and end times! The UI looks good to me, but unfortunately I don't have the skill and time to test the changes.

**Comment by te-online** [comment]
Yes! I'd like to merge it soon. My plan is to write one or two end-to-end tests as a sanity check. Should land soon 😊

**Pull request merged**
